POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Test new",
    "number": "123-12345"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Test new"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "1234"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Ada Lovelace",
    "number": " 10-22-334455"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Ad",
    "number": "5468585"
}